/** @type {import('stylelint').Config} */
const config = {
  extends: "stylelint-config-standard",
  plugins: ["stylelint-order"],
  rules: {
    // Disable rules that conflict with project conventions
    "no-descending-specificity": null,
    "property-no-vendor-prefix": null,

    // 5-group CSS property order (styles instructions)
    // Properties sorted alphabetically within each group
    "order/properties-order": [
      [
        // Group 1: Position / z-index
        {
          groupName: "position",
          noEmptyLineBetween: true,
          properties: ["bottom", "left", "position", "right", "top", "z-index"],
        },

        // Group 2: Display / flex / grid
        {
          emptyLineBefore: "threshold",
          groupName: "display",
          noEmptyLineBetween: true,
          properties: [
            "align-content",
            "align-items",
            "align-self",
            "column-gap",
            "display",
            "flex",
            "flex-basis",
            "flex-direction",
            "flex-flow",
            "flex-grow",
            "flex-shrink",
            "flex-wrap",
            "gap",
            "grid",
            "grid-area",
            "grid-column",
            "grid-row",
            "grid-template",
            "grid-template-columns",
            "grid-template-rows",
            "justify-content",
            "justify-items",
            "justify-self",
            "order",
            "place-content",
            "place-items",
            "place-self",
            "row-gap",
            "visibility",
          ],
        },

        // Group 3: Box model
        {
          emptyLineBefore: "threshold",
          groupName: "box-model",
          noEmptyLineBetween: true,
          properties: [
            "border",
            "border-bottom",
            "border-color",
            "border-left",
            "border-radius",
            "border-right",
            "border-style",
            "border-top",
            "border-width",
            "box-sizing",
            "height",
            "margin",
            "margin-bottom",
            "margin-left",
            "margin-right",
            "margin-top",
            "max-height",
            "max-width",
            "min-height",
            "min-width",
            "overflow",
            "overflow-x",
            "overflow-y",
            "padding",
            "padding-bottom",
            "padding-left",
            "padding-right",
            "padding-top",
            "width",
          ],
        },

        // Group 4: Typography
        {
          emptyLineBefore: "threshold",
          groupName: "typography",
          noEmptyLineBetween: true,
          properties: [
            "color",
            "font",
            "font-family",
            "font-size",
            "font-style",
            "font-weight",
            "letter-spacing",
            "line-height",
            "text-align",
            "text-decoration",
            "text-overflow",
            "text-transform",
            "white-space",
            "word-break",
            "word-wrap",
          ],
        },

        // Group 5: Visual
        {
          emptyLineBefore: "threshold",
          groupName: "visual",
          noEmptyLineBetween: true,
          properties: [
            "-webkit-background-clip",
            "-webkit-text-fill-color",
            "animation",
            "animation-delay",
            "animation-direction",
            "animation-duration",
            "animation-fill-mode",
            "animation-iteration-count",
            "animation-name",
            "animation-play-state",
            "animation-timing-function",
            "background",
            "background-clip",
            "background-color",
            "background-image",
            "background-position",
            "background-repeat",
            "background-size",
            "box-shadow",
            "cursor",
            "filter",
            "object-fit",
            "object-position",
            "opacity",
            "outline",
            "pointer-events",
            "resize",
            "transform",
            "transition",
            "user-select",
            "will-change",
          ],
        },
      ],
      {
        emptyLineBeforeUnspecified: "threshold",
        emptyLineMinimumPropertyThreshold: 999,
        unspecified: "bottomAlphabetical",
      },
    ],
  },
};

export default config;
